#!/bin/bash
set -e
shopt -s nullglob

PROGNAME="efistub-sync"
VERSION="0.1.0"

#---help---
# Usage: efistub-sync all
#        efistub-sync <kernel> [<kernel>...]
#        efistub-sync <-h | -V>
# 
# Synchronise the EFI Unified Kernel Images on EFI partition with the kernel / commandline / initrd / microcode
# currently installed on the system; intended to be run after any change to these components, in order to remove
# need for additional bootloaders.
# 
# When run, generates the EFI Unified Kernel Image, then puts it in target directory (defaults to /boot/efi/EFI)
# for access via boot entry. If the older image is in place, it gets renamed and kept as backup, up to configured
# number of backups (defaults to 3).
# 
# Complimentary Pacman hook ensures the automatic synchronisation when the kernel files, microcode, or initcpio
# components are modified during installation/update, but should be run manually for manual updates to initramfs,
# or to preferred command line.
#
# Arguments:
#   all                  If given this argument, synchronises EFI image for every kernel currently installed.
#   <kernel>...          Package name for the kernel to synchronise, such as "linux" or "linux-tkg"; multiple may be specified.
# 
# Options:
#   -h                   Show this message and exit.
#   -V                   Show version and exit.
# 
# Additional configuration (target directory for EFI images, source of kernel command line, and how many) can be done
# by modifying the configuration file at /etc/efistub-sync.conf.
#---help---

help() {
	sed -n '/^#---help---/,/^#---help---/p' "$0" | sed 's/^# \?//; 1d;$d;'
}

while getopts ':hV' OPT; do
	case "$OPT" in
		h) help; exit 0;;
		V) echo "$PROGNAME $VERSION"; exit 0;;
		\?) echo "unknown option: -$OPTARG" 1>&2; exit 1;;
	esac
done

# SETTINGS
TARGET_DIR=/boot/efi/EFI
COMMAND_LINE="/proc/cmdline"
OLD_STUBS_LIMIT=3

# Attempt to load the configuration file, if it's available
if [ -r "/etc/efistub-sync.conf" ]; then
	source "/etc/efistub-sync.conf"
fi

kernels=()
all_kernels=0

# Process the arguments given; shift all of them out - if any of the arguments is "all",
# then we go the route of grabbing all valid identifiers; otherwise we check the arguments
# against available mkinitcpio presets and add them to the list of stubs to sync if valid.
while (( "$#" )); do

	if [ "$1" == "all" ]; then
		all_kernels=1
		break
	fi

	if [[ -f "/etc/mkinitcpio.d/$1.preset" ]]; then
		kernels+=("$1")
	else
		echo "$1 is not a valid kernel name" 1>&2
	fi

	shift

done

# If processing all kernels, go by all the presents for mkinitcpio available.
if (( all_kernels )); then

	kernels=()
	while read -r line; do
		kernels+=("$(basename "${line%.preset}")")
	done < <(ls "/etc/mkinitcpio.d/"*.preset)

fi

# If the list of kernels is empty by now, something's wrong; print the error message
# and quit with error code (either the names given on the command line are invalid,
# or there are no valid mkinitcpio presets).
if [ "${#kernels[@]}" -lt 1 ]; then
	echo "No valid kernels to synchronise" 1>&2
	exit 1
fi

# Get the list of all microcode images currently residing in boot;
# they will be concatenated with initramfs into the EFISTUB, to ensure
# early loading of such fixes
readarray -t microcode < <(ls /boot/*ucode*)

# Create temporary directory for all the operations, and ensure it's correctly
# cleaned up and removed when the whole process is complete
tmpdir="$(mktemp -dt stubsync.XXXXXX)"
trap "rm -f $tmpdir/*; rmdir $tmpdir" EXIT HUP INT TERM

for kernel in "${kernels[@]}"; do

	echo "==> Updating EFISTUB for $kernel..."
	echo "    Generating EFISTUB file..."
	efi-mkuki -o "$tmpdir/efistub-$kernel.img" -c "$COMMAND_LINE" "/boot/vmlinuz-$kernel" "${microcode[@]}" "/boot/initramfs-$kernel.img"

	# Here we'll add Secure Boot signing

	checksum_new="$(sha256sum -b "$tmpdir/efistub-$kernel.img" | awk '{print $1}')"

	# If we don't have any previous stub of that type, just drop it into the expected location
	if [ ! -f "$TARGET_DIR/$kernel.efi" ]; then
		echo "    Deploying new EFISTUB..."
		mv "$tmpdir/efistub-$kernel.img" "$TARGET_DIR/$kernel.efi"
		echo "    EFISTUB files synchronised for $kernel"
	else

		readarray -t existing_stubs < <(ls "$TARGET_DIR/$kernel.efi"*)
		readarray -t existing_checksums < <(sha256sum "${existing_stubs[@]}" | awk '{print $1}')

		# State variable for how to proceed with the whole process:
		# 0 - we've found a match in active EFISTUB, meaning we don't have to do anything
		# 1 - we've found no match; existing files stay, new file is prepended to the beginning of the list
		# 2 - we've found a match in one of backups, need to renumerate the files so that that backup is active file
		renumerate=1

		for i in "${!existing_stubs[@]}"; do
			# Found match for the new file, perform reassignments if need be
			if [ "$checksum_new" == "${existing_checksums[$i]}" ]; then

				# If it matches the currently active EFISTUB, we don't do anything
				if [ "$i" == 0 ]; then
					echo "    Identical EFISTUB already deployed, no further action needed"
					renumerate=0
					break

				# If it matches a backup, we should move it to the beginning of the list
				# (so that it's renamed to the active EFISTUB is is thus being used)

				# If the last file in the array is matched, we've got one procedure to
				# shift it to the beginning; we "pop" it with unset, then redefine the array
				# with it at the beginning
				elif [ "$i" == "$(( "${#existing_stubs[@]}" - 1 ))" ]; then
					stub_to_move="${existing_stubs[$i]}"
					unset "existing_stubs[$i]"
					existing_stubs=("$stub_to_move" "${existing_stubs[@]}")
					echo "    EFISTUB already among backup files, reactivating it..."
					renumerate=2

				# If the item is matched in the middle of the array, then we pull it out
				# by redefining the array with two slices (one before, one after the items)
				else
					stub_to_move="${existing_stubs[$i]}"
					existing_stubs=("$stub_to_move" "${existing_stubs[@]:0:$i}" "${existing_stubs[@]:$((i+1)):${#existing_stubs[@]}}")
					echo "    EFISTUB already among backup files, reactivating it..."
					renumerate=2
				fi

			fi
		done

		# If we found no matches, prepend the file in temp directory to the list, so that
		# it gets moved to target directory and made active EFISTUB during renumeration
		if [ "$renumerate" == 1 ]; then
			echo "    Deploying new EFISTUB..."
			existing_stubs=("$tmpdir/efistub-$kernel.img" "${existing_stubs[@]}")
			renumerate=2
		fi

		if [ "$renumerate" == 2 ]; then

			for (( i=${#existing_stubs[@]}-1 ; i>=0 ; i-- )) ; do

				if [ "$i" -gt "$OLD_STUBS_LIMIT" ]; then

					# Only print the message about removing the files on the very
					# last element of the array; this guarantees that it's only going to be
					# printed once
					if [ "$i" == "$(( "${#existing_stubs[@]}" - 1 ))" ]; then
						echo "    Removing old EFISTUB backups..."
					fi
					rm "${existing_stubs[$i]}"

				else

					target_file="$TARGET_DIR/$kernel.efi$([ "$i" == 0 ] && echo "" || echo ".$i")"
					# We want to avoid clashes with movement overriding existing files,
					# so if destination file exists, add a suffix that will be removed in
					# additional pass
					if [ -f "$target_file" ]; then
						target_file="$target_file.temp"
					fi

					mv "${existing_stubs[$i]}" "$target_file"

				fi

			done

			# Remove any temporary prefixes added to prevent overriding files
			for item in "$TARGET_DIR/$kernel.efi"*.temp; do
				mv "$item" "${item%.temp}"
			done

			echo "    EFISTUB files synchronised for $kernel"
		fi

	fi

done
